package com.soecode.fzc.entity;

import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table appointment
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class AppointmentKey extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appointment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * 图书ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.book_id
     *
     * @mbg.generated
     */
    private Long bookId;
    /**
     * Database Column Remarks:
     * 学号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.student_id
     *
     * @mbg.generated
     */
    private Long studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.book_id
     *
     * @return the value of appointment.book_id
     * @mbg.generated
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.book_id
     *
     * @param bookId the value for appointment.book_id
     * @mbg.generated
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.student_id
     *
     * @return the value of appointment.student_id
     * @mbg.generated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.student_id
     *
     * @param studentId the value for appointment.student_id
     * @mbg.generated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bookId=").append(bookId);
        sb.append(", studentId=").append(studentId);
        sb.append("]");
        return sb.toString();
    }
}